Fatal error: Uncaught CustomException: Exception message in %s:%d
Stack trace:
#0 {main}
  thrown in %s on line %d