Call fail()

Fatal error: Uncaught Error: Call to protected method pass::fail() from context '' in %s:%d
Stack trace:
#0 {main}
  thrown in %s on line %d