
---- EXPECTED OUTPUT
Exception: 1 in %s:%d
Stack trace:
#0 [internal function]: gen()
#1 %s(%d): Generator->rewind()
#2 {main}

Next Exception: 2 in %s:%d
Stack trace:
#0 %s(%d): gen()
#1 {main}
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory
Exception: 1 in /root/php-src/Zend/tests/try/bug71604_3.php:5
Stack trace:
#0 [internal function]: gen()
#1 /root/php-src/Zend/tests/try/bug71604_3.php(19): Generator->rewind()
#2 {main}

Next Exception: 2 in /root/php-src/Zend/tests/try/bug71604_3.php:11
Stack trace:
#0 /root/php-src/Zend/tests/try/bug71604_3.php(19): gen()
#1 {main}
---- FAILED
