
---- EXPECTED OUTPUT
Exception: 1 in %s:%d
Stack trace:
#0 %s(%d): test()
#1 {main}

Next Exception: 3 in %s:%d
Stack trace:
#0 %s(%d): test()
#1 {main}
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory
Exception: 1 in /root/php-src/Zend/tests/try/try_finally_024.php:5
Stack trace:
#0 /root/php-src/Zend/tests/try/try_finally_024.php(21): test()
#1 {main}

Next Exception: 3 in /root/php-src/Zend/tests/try/try_finally_024.php:15
Stack trace:
#0 /root/php-src/Zend/tests/try/try_finally_024.php(21): test()
#1 {main}
---- FAILED
