
---- EXPECTED OUTPUT
Fatal error: Uncaught Exception in %s:%d
Stack trace:
#0 %s(%d): Element->ThrowException()
#1 [internal function]: Element::CallBack(Object(Element))
#2 %s(%d): array_map(Array, Array)
#3 {main}
  thrown in %s on line %d
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Exception in /root/php-src/ext/standard/tests/array/bug35821.php:7
Stack trace:
#0 /root/php-src/ext/standard/tests/array/bug35821.php(12): Element->ThrowException()
#1 [internal function]: Element::CallBack(Object(Element))
#2 /root/php-src/ext/standard/tests/array/bug35821.php(17): array_map(Array, Array)
#3 {main}
  thrown in /root/php-src/ext/standard/tests/array/bug35821.php on line 7
---- FAILED
