before yield
after yield

Exception: Cannot rewind a generator that was already run in %s:%d
Stack trace:
#0 %s(%d): Generator->rewind()
#1 {main}

Exception: Cannot traverse an already closed generator in %s:%d
Stack trace:
#0 {main}

in generator