
---- EXPECTED OUTPUT
Fatal error: Uncaught Error: Impossible to yield from the Generator being currently run in %s:%d
Stack trace:
#0 [internal function]: gen()
#1 %s(%d): Generator->send(Object(Generator))
#2 {main}
  thrown in %s on line %d
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Error: Impossible to yield from the Generator being currently run in /root/php-src/Zend/tests/generators/yield_from_already_running.php:4
Stack trace:
#0 [internal function]: gen()
#1 /root/php-src/Zend/tests/generators/yield_from_already_running.php(7): Generator->send(Object(Generator))
#2 {main}
  thrown in /root/php-src/Zend/tests/generators/yield_from_already_running.php on line 4
---- FAILED
