
---- EXPECTED OUTPUT
Fatal error: Uncaught Exception in %s:%d
Stack trace:
#0 [internal function]: crash()
#1 %s(%d): iterator_to_array(Object(Generator))
#2 {main}
  thrown in %s on line %d
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Exception in /root/php-src/Zend/tests/bug69599.php:5
Stack trace:
#0 [internal function]: crash()
#1 /root/php-src/Zend/tests/bug69599.php(9): iterator_to_array(Object(Generator))
#2 {main}
  thrown in /root/php-src/Zend/tests/bug69599.php on line 5
---- FAILED
